### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by outlookerr** [zimenglan-sysu-512/deep-flow#3]
I have installed caffe,should I install caffe again?
What is googletools?I can not find it.

**Comment by outlookerr** [comment]
Thanks for your any help

**Comment by zimenglan-sysu-512** [comment]
no need to re-install caffe if u don't do any modification on caffe. u can use soft-link to link your installed caffe to here.
good luck.

**Comment by outlookerr** [comment]
@zimenglan-sysu-512  thank u! But I have a new error when I make all in deep_matching.
fatal error: hdf5.h: 没有那个文件或目录(means no such file)
I have installed caffe sucessfully ,should I change anything to the Makefile?

**Comment by outlookerr** [comment]
Thanks u！
I  have solved this problem by add "-I/usr/include/hdf5/serial" to the include of makefile.
becourse I use ubuntu16.04(maybe)
